name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read         # нужно чтобы checkout прошёл
  packages: write        # нужно чтобы пушить в ghcr.io

jobs:
  build-and-test:
    name: "Build & Test all microservices"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - airport-boarding-service
          - airport-bookings-service
          - airport-checkin-service
          - airport-checking-service
          - airport-flight-service
          - airport-pilot-service
          - api-gateway
          - eureka-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Maven test & package
        working-directory: ${{ matrix.service }}
        run: mvn -B -q clean test package

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ matrix.service }}
          docker build \
            -t $IMAGE_NAME:ci-${{ github.sha }} \
            ./${{ matrix.service }}

      # логинимся в GHCR только на пуш в main (не для pull_request)
      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # пушим тоже только на пуш в main
      - name: Push image to GHCR
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=${{ matrix.service }}

          docker tag $IMAGE_NAME:ci-${{ github.sha }} ghcr.io/$OWNER/$IMAGE_NAME:${{ github.sha }}
          docker push ghcr.io/$OWNER/$IMAGE_NAME:${{ github.sha }}
